### ISSUE TITLE
When SPLIT address is defined other set addresses are ignored

### ISSUE THREAD

**Issue by crackfoo** [simplecrypto/simplecoin_multi#194]
When a miner utilizes the SPLIT payout feature all the coins they have had set to get direct payouts, are then exchanged at the set % of the split.

So, if you split 100% to another currency, then all your earning are then exchanged for the SPLIT coin and you get none of the coins you had set to keep.

Is this a bug or expected? I was under the impression that if you had addresses set you would get thosd coins regardless of any SPLIT %.

Thanks

**Comment by ericecook** [comment]
This is working as intended. The split payout feature is designed to work on the totality of your mining rather than a subset. This is handy for people that want to do things like donate 2% of their mining to a charity.

It could be modified to work as you describe, but be careful when modifying the payout code!
